# -*- coding: utf-8 -*-
"""Bfs&Dfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYZMO5l1dLNvH36IgccisqwbsMPHKj8B
"""

# BFS and DFS test (simple version)

graph = {
    0: [2, 4, 5],
    1: [4],
    2: [3],
    3: [],
    4: [2],
    5: [1, 4]
}

def bfs(start, graph):
    visited = []
    queue = [start]
    while queue:
        node = queue.pop(0)
        if node not in visited:
            visited.append(node)
            queue.extend(graph[node])
    return visited

def dfs(start, graph):
    visited = []
    stack = [start]
    while stack:
        node = stack.pop()
        if node not in visited:
            visited.append(node)
            stack.extend(reversed(graph[node]))
    return visited

print("BFS Traversal:", bfs(0, graph))
print("DFS Traversal:", dfs(0, graph))