# -*- coding: utf-8 -*-
"""Lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtOohF4eEm5eK4JI-V4rVpPXN6wNyGzh
"""



"""## **Lists**"""

!pip install numpy

#Create a list of 10 Integers
numbers=[2,10,23,5,89,67,34,22,11,90]
print('Original List:' ,numbers)

#Sum,max and min
print('Sum:' , sum(numbers))
print('Max:' , max(numbers))
print('Min:' , min(numbers))

#Add a new element to the list and remove an existing one
numbers.append(50)
numbers.remove(23)
print('updated List:' , numbers)

#sort list in Assending And descending order
print('Ascending:', sorted(numbers))
print('Descending', sorted(numbers,reverse=True))

"""# **Tuples**"""

#Create a tuple with 5 strings
fruits =('apple', 'banana','cherry','mango','grapes')

#print 2nd and last element
print('Second Element:',fruits[1])
print('Last Element:',fruits[-1])

#try to remove or check
#fruits.remove('apple')

#convert tuple to list
fruit_list=list(fruits)
fruit_list[2]='orange'
print('Modified List:' ,fruit_list)

"""# **Sets**"""

#Create sets
set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}
#Union,Intersection,Difference
print('Union:',set_a | set_b)
print('Intersection:')

"""# **Dictionaries**"""

#create dictionary
students = {'Ali':85,'Sara':90,'Ahmed':78,'Zara':92,'Omar':88}

#print keys and values
print('keys:', students.key())
print('Values:', students.values())

#update value
students['Ali']

"""# **Numpy**

# **Matplotlib**
"""