# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhnvUoa44SgkPX6t5yTE0hsZpoVIPHmE
"""



"""# New Section"""

a=10
b=20
sum = a+b
print("The Sum =",sum)

"""# New Section"""

a=10
b=20
subt = a-b
print("The Substraction =",subt)

"""# New Section"""

a=10
b=20
div = a+b
print("The Division =",div)

"""# New Section"""

from re import MULTILINE
a=10
b=20
multi = a+b
print("The Multiplication =",multi)